// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  GetChatDetailsData,
  GetChatDetailsResponses,
  GetChatsData,
  GetChatsResponses,
  GetCurrentUserData,
  GetCurrentUserResponses,
  GetOnlineUsersData,
  GetOnlineUsersResponses,
  GetUsersData,
  GetUsersResponses,
  LoginData,
  LoginResponses,
  RegisterData,
  RegisterResponses,
  StartGroupChatData,
  StartGroupChatResponses,
  StartPrivateChatData,
  StartPrivateChatResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export const startPrivateChat = <ThrowOnError extends boolean = true>(
  options: Options<StartPrivateChatData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    StartPrivateChatResponses,
    unknown,
    ThrowOnError
  >({
    url: "/chats/private",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const startGroupChat = <ThrowOnError extends boolean = true>(
  options: Options<StartGroupChatData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    StartGroupChatResponses,
    unknown,
    ThrowOnError
  >({
    url: "/chats/group",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const register = <ThrowOnError extends boolean = true>(
  options: Options<RegisterData, ThrowOnError>,
) =>
  (options.client ?? client).post<RegisterResponses, unknown, ThrowOnError>({
    url: "/auth/register",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const login = <ThrowOnError extends boolean = true>(
  options: Options<LoginData, ThrowOnError>,
) =>
  (options.client ?? client).post<LoginResponses, unknown, ThrowOnError>({
    url: "/auth/login",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

export const getUsers = <ThrowOnError extends boolean = true>(
  options?: Options<GetUsersData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetUsersResponses, unknown, ThrowOnError>({
    url: "/users",
    ...options,
  });

export const getOnlineUsers = <ThrowOnError extends boolean = true>(
  options?: Options<GetOnlineUsersData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetOnlineUsersResponses,
    unknown,
    ThrowOnError
  >({ url: "/users/online", ...options });

export const getChats = <ThrowOnError extends boolean = true>(
  options?: Options<GetChatsData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetChatsResponses, unknown, ThrowOnError>({
    url: "/chats",
    ...options,
  });

export const getChatDetails = <ThrowOnError extends boolean = true>(
  options: Options<GetChatDetailsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetChatDetailsResponses,
    unknown,
    ThrowOnError
  >({ url: "/chats/{chatId}", ...options });

/**
 * Get information about the logged in user
 */
export const getCurrentUser = <ThrowOnError extends boolean = true>(
  options?: Options<GetCurrentUserData, ThrowOnError>,
) =>
  (options?.client ?? client).get<
    GetCurrentUserResponses,
    unknown,
    ThrowOnError
  >({ url: "/auth/me", ...options });
