CREATE TABLE chats (
    id UUID PRIMARY KEY,
    name VARCHAR(100),
    type VARCHAR(10) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);